# fly.toml app configuration file generated for statusfer on 2023-08-30T15:39:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "statusfer"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
